### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flodef**
Change the app opening adress as it was displaying solana pay logo, instead of the real app.

### CODE REVIEW

**Comment by jordansexton** [comment]
This is by design. It will redirect to `/new` if valid query params are provided. Check our label and recipient query params to make sure they are correct.

**Comment by flodef** [comment]
You're right, just tested, it worked !
I find it a bit confusing anyway. Thanks for the quick answer.
And keep up the good work.

**Comment by jordansexton** [comment]
Here's where we check for the params: https://github.com/solana-labs/solana-pay/blob/fb40bfc0a3a43824a4657b3d2a0ba67d3867c09f/point-of-sale/src/components/routes/RootRoute.tsx#L26-L42

Here's where we do the redirect: https://github.com/solana-labs/solana-pay/blob/fb40bfc0a3a43824a4657b3d2a0ba67d3867c09f/point-of-sale/src/components/routes/RootRoute.tsx#L26-L42

The redirect will only occur if the params are provided, and especially if the recipient is a valid pubkey.

**Comment by flodef** [comment]
I see. That sure helps a lot !! Thank you :-D

**Pull request closed without merging**
