### PR TITLE
update spec

### PR DESCRIPTION
**Pull request by mariusbld**

### CODE REVIEW

**Comment by jordansexton** [comment]
I think you're opening this PR to the wrong repo.

**Comment by mariusbld** [comment]
> I think you're opening this PR to the wrong repo.

Oh yeah, I meant to open it in against my fork, but the Github UI defaults to the original repo..

**Comment by jordansexton** [comment]
I know that feel...

**Comment by mariusbld** [comment]
@jordansexton what's the best way to chat? We're building rewards on top of Solana pay and it would be really cool if there was a Solana Pay Shopify Plugin. 
I saw your Shopify branch but wanted to know what's the latest with it, so we can integrate - I know Shopify is picky about creating a new payment app

**Comment by jordansexton** [comment]
Check out the solana-pay channel on Discord!

**Pull request closed without merging**
