### PR TITLE
update cd to 'solana-pay' for Github CLI

### PR DESCRIPTION
**Pull request by jcstein**
This is an update to the `cd` command for the Github CLI version

### CODE REVIEW

**Comment by jordansexton** [comment]
Thanks!

**Comment by jcstein** [comment]
You're welcome! Thanks for cleaning it up 😊

**Comment by jcstein** [comment]
Any idea what I may be doing wrong here? Thank you!

scrot 2022-02-01 at 10 22 15 PM
!

**Comment by jordansexton** [comment]
@jcstein I've seen this kind of thing happen if you end up with two different versions of some dependency. What I would do is run `yarn nuke` and then `yarn install` from the point-of-sale directory to see if it fixes it.

**Comment by jcstein** [comment]
thank you @jordansexton! This makes sense now. I think what (may have) happened is that I ran `yarn install` in the `solana-pay` directory and then again in `point-of-sale` more than once after I ran into this issue.

**Comment by jordansexton** [comment]
Yeahhh, I think it might be good for us to set up yarn workspaces or something if we're going to continue to use a monorepo so that dependencies get properly linked / deduped.

**Comment by jcstein** [comment]
sounds good, thanks again. I'm still learning, but this makes sense. please forgive me if I am asking too much 😅 . I've got things running successfully, what would be the next steps to set myself up to test out a transaction?

scrot 2022-02-01 at 11 01 34 PM

**Comment by jcstein** [comment]
got it running! gn ✌️ and thanks again @jordansexton

**Comment by jordansexton** [comment]
Glad you got it working!

**Pull request merged**
